# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 11:03
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import gift_ru.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок страницы')),
                ('seo_text', ckeditor.fields.RichTextField(blank=True, verbose_name='Сео текст на главной')),
                ('slider_images', models.ImageField(upload_to=gift_ru.models.FilePathPhotos)),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='заголовок')),
                ('meta_keywords', models.CharField(blank=True, max_length=250, verbose_name='ключевые слова')),
                ('meta_description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
        ),
    ]
