# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_ru', '0004_stepby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepby',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Заголовок шага'),
        ),
    ]
