# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_ru', '0005_auto_20171006_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepby',
            name='sort',
            field=models.IntegerField(default=10, verbose_name='Номер шага'),
        ),
    ]
