# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_ru', '0006_stepby_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='alt',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
