# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('url', models.CharField(max_length=75, verbose_name='url')),
                ('visible', models.BooleanField(default=True, verbose_name='отображать')),
                ('order', models.IntegerField(default=10, verbose_name='порядок сортировки')),
            ],
            options={
                'verbose_name_plural': 'меню',
                'ordering': ['-order', 'pk'],
                'verbose_name': 'меню',
            },
        ),
    ]
