# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170930_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
