# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 20:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(help_text='Адрес страницы на латинице. Например, "your_address"', max_length=200, unique=True, verbose_name='Адрес')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Содержимое страницы')),
                ('order', models.IntegerField(default=10, verbose_name='Порядок сортировки')),
                ('template', models.CharField(default='default.html', max_length=100, verbose_name='шаблон')),
                ('visible', models.BooleanField(default=True, verbose_name='отображать')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='заголовок')),
                ('meta_keywords', models.CharField(blank=True, max_length=250, verbose_name='ключевые слова')),
                ('meta_description', models.TextField(blank=True, verbose_name='описание')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('changed', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name_plural': 'страницы',
                'verbose_name': 'страница',
            },
        ),
    ]
