# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_page_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.CharField(default='default.html', max_length=100, verbose_name='шаблон'),
        ),
    ]
