# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_in_header',
            field=models.BooleanField(default=True, verbose_name='отображать в шапке'),
        ),
    ]
