# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20171008_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='template',
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Родительская страница'),
            preserve_default=False,
        ),
    ]
