# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20171031_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Родительская страница'),
        ),
    ]
