# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksimage',
            name='is_big',
            field=models.BooleanField(default=False),
        ),
    ]
