# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('slug', models.SlugField(help_text='Адрес категории на латинице. Например, "your_address"', max_length=250, unique=True, verbose_name='Адрес')),
                ('vendor_code', models.IntegerField(blank=True, default=None, unique=True, verbose_name='Артикул')),
                ('price', models.FloatField(blank=True, default=0.0, verbose_name='Цена')),
                ('brand', models.CharField(blank=True, max_length=128, null=True, verbose_name='Бренд')),
                ('weight', models.CharField(max_length=256, null=True, verbose_name='Вес')),
                ('size', models.CharField(max_length=256, null=True, verbose_name='Размер')),
                ('material', models.CharField(max_length=256, null=True, verbose_name='Материал')),
                ('density', models.CharField(max_length=256, null=True, verbose_name='Плотность')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='заголовок')),
                ('meta_keywords', models.CharField(blank=True, max_length=250, verbose_name='ключевые слова')),
                ('meta_description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('changed', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('slug', models.SlugField(help_text='Адрес категории на латинице. Например, "your_address"', max_length=250, unique=True, verbose_name='Адрес')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='заголовок')),
                ('meta_keywords', models.CharField(blank=True, max_length=250, verbose_name='ключевые слова')),
                ('meta_description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('changed', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.ProductCategory')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.FilePathPhotos)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory', verbose_name='категория'),
        ),
    ]
