# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 15:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('full_name', models.CharField(blank=True, default=None, max_length=258, null=True)),
                ('slug', models.SlugField(help_text='Адрес категории на латинице. Например, "your_address"', max_length=250, unique=True, verbose_name='Адрес')),
                ('description', models.TextField(default=None, null=True, verbose_name='Описание')),
                ('vendor_code', models.CharField(blank=True, default=None, max_length=250, unique=True, verbose_name='Артикул')),
                ('price', models.FloatField(blank=True, default=0.0, verbose_name='Цена')),
                ('discount_price', models.FloatField(blank=True, default=0.0, verbose_name='Скидочная цена')),
                ('brand', models.CharField(blank=True, max_length=128, null=True, verbose_name='Бренд')),
                ('branding', models.CharField(blank=True, max_length=128, null=True, verbose_name='Брендинг')),
                ('size', models.CharField(blank=True, max_length=256, null=True, verbose_name='Размер')),
                ('material', models.CharField(blank=True, max_length=256, null=True, verbose_name='Материал')),
                ('source', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя магазина товара')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='заголовок')),
                ('meta_keywords', models.CharField(blank=True, max_length=250, verbose_name='ключевые слова')),
                ('meta_description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('changed', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('slug', models.SlugField(help_text='Адрес категории на латинице. Например, "your_address"', max_length=250, unique=True, verbose_name='Адрес')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to=products.models.FilePathPhotos)),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='заголовок')),
                ('meta_keywords', models.CharField(blank=True, max_length=250, verbose_name='ключевые слова')),
                ('meta_description', models.TextField(blank=True, verbose_name='описание')),
                ('seo_text_top', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст сверху страницы')),
                ('seo_text_bottom_left', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст внизу слева')),
                ('seo_text_bottom_right', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст внизу справа')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('changed', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.ProductCategory')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=128, null=True, verbose_name='Цвет')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': 'Цвет товара',
                'verbose_name_plural': 'Цвета товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.FilePathPhotos)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
