# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='25', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory', verbose_name='категория'),
        ),
    ]
