# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя атрибута')),
                ('value', models.CharField(blank=True, max_length=64, null=True, verbose_name='Значение атрибута')),
                ('dim', models.CharField(blank=True, max_length=64, null=True, verbose_name='Величина атрибута')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': 'Атрибут товара',
                'verbose_name_plural': 'Атрибуты товаров',
            },
        ),
    ]
