# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171005_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='density',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Плотность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Вес'),
        ),
    ]
