# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171005_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Старая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Старая цена'),
        ),
    ]
