# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171031_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory', verbose_name='Категории'),
        ),
    ]
