# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171005_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Скидочная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, default=None, max_length=250, unique=True, verbose_name='Артикул'),
        ),
    ]
