# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171005_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя магазина товара'),
        ),
    ]
