# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_producttocategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ID группы товаров'),
        ),
    ]
