# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.FilePathPhotos),
        ),
    ]
