# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 18:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productcategory_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='seo_text_bottom_left',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст внизу слева'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='seo_text_bottom_right',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст внизу справа'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='seo_text_top',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Текст сверху страницы'),
        ),
    ]
