# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20171008_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Бренд')),
                ('slug', models.SlugField(help_text='Адрес бренда на латинице. Например, "your_address"', max_length=250, unique=True, verbose_name='Адрес')),
                ('logotype', models.ImageField(upload_to='static/uploads/brand')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductBrand'),
        ),
    ]
