# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, verbose_name='Имя')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('is_active', models.BooleanField(default=1, verbose_name='Отображать')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'verbose_name': 'Отзыв о товаре',
            },
        ),
    ]
