# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Отображать'),
        ),
    ]
