# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(blank=True, default=5, verbose_name='Оценка отзыва'),
        ),
    ]
