# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20171009_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, default=25, to='products.ProductCategory', verbose_name='Категории'),
        ),
    ]
